sudo: required
services:
    - docker
before_install:
    - docker build -t gauravkhedekar/react-app -f Dockerfile.dev .
script:
    - docker run -t gauravkhedekar/react-app npm run test -- --coverage
