sudo: required
services:
    - docker
before_install:
    - docker build -t gauravkhedekar/react-app -f Dockerfile.dev .
    - gem install bundler
#script:
#    - docker run gauravkhedekar/react-app npm run test -- --coverage
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "react-app"
    env: "ReactApp-env"
    bucket_name: "elasticbeanstalk-ap-south-1-558760945294"
    bucket_path: "react-app"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"
