sudo: required
services:
    - docker
before_install:
    - docker build -t gauravkhedekar/react-app -f Dockerfile.dev .
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "AKIAYEGF7M2HK5MCHUGM"
  secret_access_key:
    secure: "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"
  region: "ap-south-1"
  app: "react-app"
  env: "Docker-env"
  bucket_name: "elasticbeanstock-ap-south-1-12345"
  bucket_path: "docker"
  on:
    branch: master
